require("config.lazy")
vim.cmd.colorscheme("roseprime")
require("lspconfig").jdtls.setup({})
-- require("mini.statusline").setup({})
require("el").setup({})
vim.lsp.enable({ "lua_ls", "jdtls", "ts_ls" })
