#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true

#Autostart applications
# ibus-daemon -rxRd &
# ibus restart &
xsetroot -cursor_name left_ptr &
polybar &
dunst &
nitrogen --restore &

#Configuration
bspc config top_padding 0
bspc config border_width 0 #2
bspc config window_gap 0   #12
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0
#### BSPWM coloring ####
bspc config normal_border_color "#4c566a"
bspc config active_border_color "#1e1e1e"
bspc config focused_border_color "#a6bcaa"
bspc config presel_feedback_color "#a6bcaa"
bspc config urgent_border_color "#dd2727"
